### ISSUE TITLE
Make automake a dependency

### ISSUE THREAD

**Issue by bennypowers** [rrthomas/cw#8] opened 2015-09-10 20:27 UTC
I ran 

```
brew install lua
...
luarocks install cw
...
LUA=/usr/local/bin/lua autoreconf -i && ./configure --prefix=/usr/local/lib/luarocks/rocks-5.2/cw/2.0.4-1 --libdir=/usr/local/lib/luarocks/rocks-5.2/cw/2.0.4-1/lib --datadir=/usr/local/lib/luarocks/rocks-5.2/cw/2.0.4-1/lua && make clean && make
sh: autoreconf: command not found

Error: Build error: Failed building.
```

so then i ran 

```
brew install automake
...
luarocks install cw
```

and it worked just dandy

**Comment by rrthomas** [comment] 2015-09-10 20:37
This issue is not OS X specific, though you could fix it by making a (trivial) brew recipe for cw.

The problem is that I know no way of adding automake as a luarocks dependency.

Thanks for the report. I shall add a note about the dependency to cw's README, and ask the luarocks folk what they think (because obviously this is an instance of a broader problem: how to deal with build dependencies in luarocks on things that aren't luarocks modules).

**Comment by rrthomas** [comment] 2019-03-10 16:03
Closing, as automake is no longer used.

**Closed by rrthomas** 2019-03-10 16:03 UTC
